//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogoMovimiento
    {
        public catalogoMovimiento()
        {
            this.MovimientosAseguradoes = new HashSet<MovimientosAsegurado>();
        }
    
        public int id { get; set; }
        public string tipo { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    
        public virtual ICollection<MovimientosAsegurado> MovimientosAseguradoes { get; set; }
    }
}
