//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class suaEntities : DbContext
    {
        public suaEntities()
            : base("name=suaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<catalogoMovimiento> catalogoMovimientos { get; set; }
        public virtual DbSet<Incapacidade> Incapacidades { get; set; }
        public virtual DbSet<MovimientosAsegurado> MovimientosAseguradoes { get; set; }
        public virtual DbSet<Parametro> Parametros { get; set; }
        public virtual DbSet<Patrone> Patrones { get; set; }
        public virtual DbSet<Acreditado> Acreditados { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<Modulo> Modulos { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<RoleModulo> RoleModulos { get; set; }
        public virtual DbSet<Movimiento> Movimientos { get; set; }
        public virtual DbSet<RoleFuncion> RoleFuncions { get; set; }
        public virtual DbSet<TopicosUsuario> TopicosUsuarios { get; set; }
        public virtual DbSet<Funcion> Funcions { get; set; }
        public virtual DbSet<Factore> Factores { get; set; }
        public virtual DbSet<Plaza> Plazas { get; set; }
        public virtual DbSet<Asegurado> Asegurados { get; set; }
        public virtual DbSet<Pago> Pagos { get; set; }
        public virtual DbSet<ResumenPago> ResumenPagoes { get; set; }
    }
}
