//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        public int id { get; set; }
        public string parametroId { get; set; }
        public string descripcion { get; set; }
        public string valorString { get; set; }
        public Nullable<decimal> valorMoneda { get; set; }
        public Nullable<System.DateTime> valorFecha { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    }
}
