//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUADATOS
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleFuncion
    {
        public int id { get; set; }
        public int roleId { get; set; }
        public int funcionId { get; set; }
        public int usuarioCreacionId { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Funcion Funcion { get; set; }
    }
}
