//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUAMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SUAMVC.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acción.
        /// </summary>
        public static string accion {
            get {
                return ResourceManager.GetString("accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acreditados.
        /// </summary>
        public static string acreditados {
            get {
                return ResourceManager.GetString("acreditados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busqueda Avanzada.
        /// </summary>
        public static string advanceSearch {
            get {
                return ResourceManager.GetString("advanceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string agregar {
            get {
                return ResourceManager.GetString("agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno.
        /// </summary>
        public static string apellidoMaterno {
            get {
                return ResourceManager.GetString("apellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        public static string apellidoPaterno {
            get {
                return ResourceManager.GetString("apellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aviso Ret..
        /// </summary>
        public static string avisoRet {
            get {
                return ResourceManager.GetString("avisoRet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar.
        /// </summary>
        public static string borrar {
            get {
                return ResourceManager.GetString("borrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string bt_cancel {
            get {
                return ResourceManager.GetString("bt_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string bt_exit {
            get {
                return ResourceManager.GetString("bt_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        public static string bt_login {
            get {
                return ResourceManager.GetString("bt_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string bt_register {
            get {
                return ResourceManager.GetString("bt_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Catalogo de.
        /// </summary>
        public static string catde {
            get {
                return ResourceManager.GetString("catde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente.
        /// </summary>
        public static string cliente {
            get {
                return ResourceManager.GetString("cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SIAP.
        /// </summary>
        public static string company_name {
            get {
                return ResourceManager.GetString("company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IMSS 3.0.
        /// </summary>
        public static string company_subtitle {
            get {
                return ResourceManager.GetString("company_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar.
        /// </summary>
        public static string consulta {
            get {
                return ResourceManager.GetString("consulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criterio.
        /// </summary>
        public static string criterio {
            get {
                return ResourceManager.GetString("criterio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuota Fija.
        /// </summary>
        public static string cuotaFija {
            get {
                return ResourceManager.GetString("cuotaFija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CURP.
        /// </summary>
        public static string curp {
            get {
                return ResourceManager.GetString("curp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Bimestral.
        /// </summary>
        public static string descBimestral {
            get {
                return ResourceManager.GetString("descBimestral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Catorcenal.
        /// </summary>
        public static string descCatorcenal {
            get {
                return ResourceManager.GetString("descCatorcenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Diario.
        /// </summary>
        public static string descDiario {
            get {
                return ResourceManager.GetString("descDiario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Mensual.
        /// </summary>
        public static string descMensual {
            get {
                return ResourceManager.GetString("descMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Quincenal.
        /// </summary>
        public static string descQuincenal {
            get {
                return ResourceManager.GetString("descQuincenal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción.
        /// </summary>
        public static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Semanal.
        /// </summary>
        public static string descSemanal {
            get {
                return ResourceManager.GetString("descSemanal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desc. Veintiochonal.
        /// </summary>
        public static string descVeintiocho {
            get {
                return ResourceManager.GetString("descVeintiocho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles de.
        /// </summary>
        public static string detallesDe {
            get {
                return ResourceManager.GetString("detallesDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factores.
        /// </summary>
        public static string factores {
            get {
                return ResourceManager.GetString("factores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar ingresar al SIAP.
        /// </summary>
        public static string failed_login {
            get {
                return ResourceManager.GetString("failed_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Alta.
        /// </summary>
        public static string fechaAlta {
            get {
                return ResourceManager.GetString("fechaAlta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Baja.
        /// </summary>
        public static string fechaBaja {
            get {
                return ResourceManager.GetString("fechaBaja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F. Fin Desc..
        /// </summary>
        public static string fFinDescuento {
            get {
                return ResourceManager.GetString("fFinDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a F.Ini.Desc..
        /// </summary>
        public static string fInicioDescuento {
            get {
                return ResourceManager.GetString("fInicioDescuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a - SIAP Sistema de Administración de Personal IMSS.
        /// </summary>
        public static string footer_title {
            get {
                return ResourceManager.GetString("footer_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funciones.
        /// </summary>
        public static string funciones {
            get {
                return ResourceManager.GetString("funciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Grupo.
        /// </summary>
        public static string grupo {
            get {
                return ResourceManager.GetString("grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SIAP Web Site.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        public static string modificar {
            get {
                return ResourceManager.GetString("modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. Afiliacion.
        /// </summary>
        public static string noAfiliacion {
            get {
                return ResourceManager.GetString("noAfiliacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No. Credito.
        /// </summary>
        public static string noCredito {
            get {
                return ResourceManager.GetString("noCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre(s).
        /// </summary>
        public static string nombre {
            get {
                return ResourceManager.GetString("nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Completo.
        /// </summary>
        public static string nombreCompleto {
            get {
                return ResourceManager.GetString("nombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocupación.
        /// </summary>
        public static string ocupacion {
            get {
                return ResourceManager.GetString("ocupacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patrón.
        /// </summary>
        public static string patron {
            get {
                return ResourceManager.GetString("patron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plaza.
        /// </summary>
        public static string plaza {
            get {
                return ResourceManager.GetString("plaza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje.
        /// </summary>
        public static string porcentaje {
            get {
                return ResourceManager.GetString("porcentaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Patronal.
        /// </summary>
        public static string registroPatronal {
            get {
                return ResourceManager.GetString("registroPatronal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registros.
        /// </summary>
        public static string registros {
            get {
                return ResourceManager.GetString("registros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RFC.
        /// </summary>
        public static string rfc {
            get {
                return ResourceManager.GetString("rfc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SD.
        /// </summary>
        public static string sd {
            get {
                return ResourceManager.GetString("sd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SDI.
        /// </summary>
        public static string sdi {
            get {
                return ResourceManager.GetString("sdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SMDF.
        /// </summary>
        public static string smdf {
            get {
                return ResourceManager.GetString("smdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subir Acuse Masivo.
        /// </summary>
        public static string subirAcuseMax {
            get {
                return ResourceManager.GetString("subirAcuseMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar a Excel.
        /// </summary>
        public static string toExcel {
            get {
                return ResourceManager.GetString("toExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        public static string ubicacion {
            get {
                return ResourceManager.GetString("ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        public static string valor {
            get {
                return ResourceManager.GetString("valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a VSM.
        /// </summary>
        public static string vsm {
            get {
                return ResourceManager.GetString("vsm", resourceCulture);
            }
        }
    }
}
